Back things up

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,35 +1,16 @@
-#!/bin/bash
+#!/bin/sh
 
-cd "$HOME"
+here="$(dirname "$0")"
+checkcmd() {
+  which -s "$@" >/dev/null
+  return $?
+}
 
-[[ -e "$HOME/README.md" ]] && rm "$HOME/README.md"
-
-yadm remote set-url origin "git@github.com:BDMorrell/dotfiles.git"
-
-if [[ "$(uname)" = "Darwin" ]]; then
-  if !( xcode-select -p >/dev/null ); then
-    echo "Installing command line tools..."
-    sudo xcode-select --install
+if checkcmd zsh; then
+  zsh "$here/bootstrap.sh"
+  if [ $? -ne 0 ]; then
+    echo "Something went wrong..."
   fi
-
-  if !( which -s brew ); then
-    echo "Installing Homebrew..."
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-  fi
-
-  if [ -f "$HOME/.Brewfile" ]; then
-    echo "Installing all of Hombrew's stuff..."
-    brew bundle --global
-    rm "$HOME/.Brewfile.lock.json"
-  fi
+else
+  echo "zsh could not be found. Can not bootstrap."
 fi
-
-if (( "$(vim --version | head -n 1 | grep -o "\d*\.\d*" | grep -o "\d" | head -n 1)" >= 8 )); then
-  VUNDLETARGET="$HOME/.vim/bundle/Vundle.vim"
-  mkdir -p "$VUNDLETARGET"
-  if [[ -z "$(ls -A "$HOME/.vim/bundle/Vundle.vim")" ]]; then
-    git clone -- https://github.com/VundleVim/Vundle.vim.git "$VUNDLETARGET"
-  fi
-fi
-
-bash "$HOME/.config/yadm/pythonInstall.sh"
